language: de
pipeline: pretrained_embeddings_spacy
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.1
  core_threshold: 0.1
  fallback_action_name: "action_default_fallback"
